import './globals.css'

import { geist, spaceGrotesk } from '@/assets/fonts'
import { ThemeProvider } from '@/provider'

import type { Metadata } from 'next'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="es" suppressHydrationWarning>
			<body
				className={`${geist.variable} ${spaceGrotesk.variable} bg-background text-foreground-light w-full font-geist antialiased`}
			>
				<ThemeProvider>{children}</ThemeProvider>
			</body>
		</html>
	)
}
