import './globals.css'

import { geist, spaceGrotesk } from '@/assets/fonts'

import type { Metadata } from 'next'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="es">
			<body
				className={`${geist.variable} ${spaceGrotesk.variable} w-full font-geist antialiased`}
			>
				{children}
			</body>
		</html>
	)
}
