import type { Metadata } from 'next'

import { Footer, Header } from '@/components'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function HomeLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<>
			<Header />
			<main className="mx-auto w-[calc(1400px+calc(2*24px))] px-6">
				{children}
			</main>
			<Footer />
		</>
	)
}
